name: Android Build and Notify

on:
  push:
    branches:
      - release/*

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug

      - name: Extract the full commit message
        run: |
          FULL_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "FULL_COMMIT_MESSAGE=${FULL_COMMIT_MESSAGE}" >> $GITHUB_ENV
          # Extract name
          COMMIT_NAME=$(echo "$FULL_COMMIT_MESSAGE" | awk -F', Message: ' '{print $1}' | awk -F': ' '{print $2}')
          echo "COMMIT_NAME=${COMMIT_NAME}" >> $GITHUB_ENV
          # Extract message
          COMMIT_MSG=$(echo "$FULL_COMMIT_MESSAGE" | awk -F', Message: ' '{print $2}')
          echo "COMMIT_MSG=${COMMIT_MSG}" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.22-7/x64
          JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.22-7/x64

      - name: Rename APK with commit message
        run: |
          APK_PATH=./app/build/outputs/apk/debug/app-debug.apk
          COMMIT_MSG=${{ env.COMMIT_MSG }}
          NEW_APK_NAME=app-debug-${COMMIT_NAME}.apk
          NEW_APK_PATH=./app/build/outputs/apk/debug/${NEW_APK_NAME}
          mv $APK_PATH $NEW_APK_PATH
          echo "NEW_APK_PATH=$NEW_APK_PATH" >> $GITHUB_ENV

      - name: Upload APK to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: 'C06H3NP3AD8'
          NEW_APK_PATH: ${{ env.NEW_APK_PATH }}
        run: |
          curl -F file=@${NEW_APK_PATH} -F "initial_comment=Here is the latest Debug APK with commit: ${{ env.COMMIT_MSG }}" -F channels=${SLACK_CHANNEL} -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" https://slack.com/api/files.upload