name: Android Build and Notify

on:
  push:
    branches:
      - release/*

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug

      - name: Get the latest commit message
        id: commit-message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -cd '[:alnum:]._-')
          echo "COMMIT_MESSAGE=$(echo $COMMIT_MESSAGE)" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Upload APK to Slack
        env:
          APK_PATH: ./app/build/outputs/apk/debug/app-debug.apk
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: 'C06H3NP3AD8'
        run: |
          curl -F file=@${APK_PATH} -F "initial_comment=Here is the latest Debug APK with commit: ${{ env.COMMIT_MESSAGE }}" -F channels=${SLACK_CHANNEL} -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" https://slack.com/api/files.upload